### ISSUE TITLE
Support for detouring P/Invoke methods?

### ISSUE THREAD

**Issue by mcpiroman** [MonoMod/MonoMod.Common#3]
Hi, I am the author of https://github.com/mcpiroman/UnityNativeTool which currently uses a copy of functionality form Harmony for the low level detour for some methods, and since Harmony was recently refactored to use this library, and I'm wondering whether it'd be beneficial if so was my project. 

The thing is, it detours the `extern` P/Invoke methods, which isn't that common situation; it worked with Harmony though. Do you have any insights if this would still work with MonoMod.Common? If so, I think that'd be better if we all used the same, shared  functionality. If you have any thoughts about this, please let me know. Anyway, thanks for working on this project.

**Comment by 0x0ade** [comment]
Welcome!

I always assumed Harmony was unable to detour extern methods, but also just realized that you're also the person who submitted a PR to Harmony to fix that 😅

The RuntimeDetour backend found in this repo (and by extension the MonoMod.RuntimeDetour NuGet package) allows you to detour both the extern method (which acts as a P/Invoke trampoline running marshalling code) and the underlying native function (you'll need to take care of marshalling on your own).

There is one notable limitation as to when you can / can't detour extern methods: the runtime / JIT can inline the P/Invoke glue code into the caller in certain circumstances, which cannot be prevented at all. To my knowledge this only affects .NET Core though, and would affect any detouring library - and as Unity is using Mono, you're not affected.  
And even if you were to be affected by that, you can still detour the actual native function.

@denikson might want to share his real world experiences on detouring native functions using RuntimeDetour so far.

Feel free to take a look at [MonoMod's NativeDetourTest](https://github.com/MonoMod/MonoMod/blob/master/MonoMod.UnitTest/RuntimeDetour/NativeDetourTest.cs) to see an example of detouring both the extern method and the native function using NativeDetour. In Harmony, similar functionality is exposed via the Memory class.

Unfortunately I'm unable to test every possible Harmony use case in my limited time, and while everything works in theory, in isolation and in other use cases, it'd be great if you could report back on whether it still works with your Harmony use case.

**Comment by denikson** [comment]
As @0x0ade pointed out, the backend this repo provides allows you to easily hook into externs. If you do so, however, it's up to you to implement the trampoline back to the original method (since often you probably actually want to call the original method). 

A good reference for implementing that is [`NativeDetour`](https://github.com/MonoMod/MonoMod/blob/master/MonoMod.RuntimeDetour/NativeDetour.cs) provided by MonoMod.RuntimeDetour (note that it's different from MonoMod.Common which is just the underlying backend code for it). If you need to be able to easily hook either to P/Invoke glue or into the actual underlying native method directly, I'd suggest to go one level higher and use NativeDetour instead.

As a real-life example, HarmonyX (a fork of Harmony) uses MonoMod.RuntimeDetour instead of MonoMod.Common as a base, which allows to easily [implement patching of extern methods](https://github.com/BepInEx/HarmonyX/blob/master/Harmony/Internal/Patching/MethodPatcher.cs#L64) with support for prefixes, postfixes, transpilers and finalizers. [It passes basic tests](https://github.com/BepInEx/HarmonyX/blob/master/HarmonyTests/Patching/NativePatching.cs) on mono, which is more than enough for Unity's usecase.

We have used NativeDetours before HarmonyX in Unity to patch externs too, and it has worked flawlessly. Just note what 0x0ade said about .NET Core and its tendency to inline P/Invoke glue.
Again, you can use MonoMod.Common to directly patch native functions just fine, but why would one do it if NativeDetour already does the same thing -- and even provides simple "trampolines" to call the original method.

**Comment by mcpiroman** [comment]
Ok, thanks, glad that it's officially covered. As to my project, for now I'll probably stick to the current solution (because I don't want to add the dependency on Mono.Cecil, as discussed on Discord), but will switch to this if things start to break. Which is quite possible btw, as Mono is constantly developed and starts to share things with .net core.
